
baseurl = "https://antweiss.com/"
languageCode = "en-us"
title = "one man's singularity"
disqusShortname = "antweiss"
disqus_url = "http://antweiss.disqus.com"
pygmentsstyle = "lovelace"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
googleAnalytics = "UA-161003981-1"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
author = "Ant Weiss"
description = "One Man's Singularity"
email = "anton@otomato.io" # TODO:
faviconfile = "img/antweiss.png"
gitHub = "antweiss" # TODO:
lang = "en"
linkedIn = "antonweiss" # TODO:
twitter = "antweiss" # TODO:
logofile = "https://avatars2.githubusercontent.com/u/3274734?s=40&v=4"
usesmallsummarycard = true
posts_navigation = true
highlightjs = true
progressively = true
share = true
latestpostcount = 5
social_banner = "img/horns-bw.png"

#[params.utteranc]
#enable = true
#repo = "antweiss/antweiss.github.io"
#issueTerm = "title"

[params.colors]
identifier = "#FFFFFF"
identifier_dark = "#CB57E0"
visited = "#CB57E0"
trivial = "#FFFFFF"
#trivial = "#6a7a8b"
foreground = "#FFFFFF"
#foreground = "#181d2a"
#background = "#f9f9f9"
background = "#323131"
background_dark = "#323131"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
hljs-comment="#29a330"